language: node_js
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

cache:
  directories:
  - node_modules
  - $HOME/.npm/_prebuilds

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - npm install codecov -g
  - echo 'Build Docs' && echo -en 'travis_fold:start:script.build\\r'

  - ng build --base-href="./"

  - echo -en 'travis_fold:end:script.build\\r'
  - echo 'Lint Codebase' && echo -en 'travis_fold:start:script.lint\\r'

  - npm run lint

  - echo -en 'travis_fold:end:script.lint\\r'
  - echo 'Test Codebase' && echo -en 'travis_fold:start:script.test\\r'

  - ng test --single-run --code-coverage

  - echo -en 'travis_fold:end:script.test\\r'
  - echo 'Package Docs' && echo -en 'travis_fold:start:script.docs\\r'

  - cd docs
  - zip -r $TRAVIS_BUILD_DIR/docs.zip *

  - cd $TRAVIS_BUILD_DIR
  - sha256sum $TRAVIS_BUILD_DIR/docs.zip > $TRAVIS_BUILD_DIR/docs.zip.sha256sum.txt
  - cat $TRAVIS_BUILD_DIR/docs.zip.sha256sum.txt

  - echo -en 'travis_fold:end:script.docs\\r'
after_success:
  - codecov
